name: clapper_counter
description: "Count clapping sounds"
version: 0.0.1+1

publish_to: 'none'

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  record: ^5.0.1
  # + record 5.0.1
  # This loads these too:
  #   + record_android 1.0.3
  #   + record_darwin 1.0.0
  #   + record_linux 0.7.1
  #   + record_platform_interface 1.0.2
  #   + record_web 1.0.3
  #   + record_windows 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Package to set your own app icon:
  #   https://pub.dev/packages/flutter_launcher_icons/versions
  #   https://www.flutterbeads.com/change-app-launcher-icon-flutter/
  #   https://icon.kitchen/
  #   /> flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  min_sdk_android: 22
  ios: true
  image_path: "assets/icons/app_icon_512x512.png"
  adaptive_icon_background: "#C7F393"
  adaptive_icon_foreground: "assets/icons/app_icon_512x512.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
