name: clapper_counter
description: "Count clapping sounds"
version: 0.0.1+1

publish_to: 'none'

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  record: ^5.0.1
  # + record 5.0.1
  # This loads these too:
  #   + record_android 1.0.3
  #   + record_darwin 1.0.0
  #   + record_linux 0.7.1
  #   + record_platform_interface 1.0.2
  #   + record_web 1.0.3
  #   + record_windows 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
